DOMAIN_BLACKLIST = [
    'msn.com',
    'bing.com',
    'bingj.com',
    'yahoo.com',
    'wikipedia.org',
    'youtube.com',
    'google.com',
    'googleadservices.com',
    'quora.com',
    'amazon.com',
    'ask.com',
    'facebook.com',
    'yandex.com',
    'yandex.ru',
]
